---
title: "Data cleaning"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r include = FALSE}
knitr::opts_chunk$set(message = FALSE)
```

## Parameters

The path to the data folder:

```{r}
data_path <- paste0("/Users/MarcChoisy/Library/CloudStorage/",
                    "OneDrive-OxfordUniversityClinicalResearchUnit/",
                    "GitHub/choisy/typhoid/")
```

## Packages

required packages:

```{r}
required_packages <- c("readxl", "dplyr")
```

Making sure that the required packages are installed:

```{r}
to_inst <- required_packages[! required_packages %in% installed.packages()[,"Package"]]
if (length(to_inst)) install.packages(to_inst)
```

Loading some of these packages:

```{r}
library(dplyr)
```

## Reading and cleaning data

The files in the raw data folder:

```{r}
files <- dir(paste0(data_path, "raw_data"), full = TRUE)
```

Reading and cleaning raw data from Nepal:

```{r}
nepal <- files[grep("nepa", files)] |>
  readxl::read_excel() |> 
  rename(WBC       = WBC_gro,
         platelets = Platelets_gro,
         vomiting  = `Vomiting...26`) |> 
  select(- contains("gro"), - contains(">"), - contains("<"), - StudyNo, - Study,
         - DateStudy, - HospitalNo, - `Vomiting...18`, - culture) |> 
  mutate(across(c(Age, Pulse, platelets, AST, ALT, Fever, Cough, Diarrhoea, vomiting,
                  Abdopain, Constipation, Headache, Anorexia, Nausea), as.integer),
         across(c(scorev1, scorev2, scorev3, scorev4, Score8),
                ~ factor(.x, ordered = TRUE)),
         across(c(Splenomegaly, Hepatomegaly),
                ~ .x == "1" | .x == "TRUE" | .x == "Yes"),
         across(Sex, ~ c("female", "male")[(.x == "1" | .x == "Male") + 1]),
         across(Typhoid_IgM,
                ~ factor(sub("N", "0", substring(.x, 1, 1)), ordered = TRUE)),
         across(`CRP_mg/L`, ~ factor(sub(" *\\(.*\\).*$", "", .x),
                                     levels = c("<10", "10-40", "40-80", ">80"),
                                     ordered = TRUE)),
         across(BloodCSResult, ~ .x == "SPA" | .x == "ST")) |> 
  select(BloodCSResult, Sex, Age, scorev1, scorev2, scorev3, scorev4, Score8,
         Fever, Cough, Diarrhoea, vomiting, Abdopain, Constipation, Headache, Anorexia,
         Nausea, Pulse, OralTemperature, Splenomegaly, Hepatomegaly, everything())
```

Reading and cleaning raw data from Cambodia and Bengladesh:

```{r}
cambodia_bangladesh <- readxl::read_excel(files[grep("camb", files)])
```

Saving to disk:

```{r}
saveRDS(nepal, paste0(data_path, "clean_data/nepal.rds"))
```


